### ISSUE TITLE
Error when using Old-Style config with list-type `stack`

### ISSUE THREAD

**Issue by nickgarber** [amendlik/gitstack-pillar#10]
When using the older config style with a list in the `stack` keyword, an error is produced: 

`[CRITICAL] Pillar render error: Failed to load ext_pillar gitstack: local variable 'stack_config_kwargs' referenced before assignment`

Here's an example of the gitstack config I'm using:
```
ext_pillar:
  - git:
    - master https://github.com/genesis-matrix/gema-plr-core
  - gitstack:
      repo: https://github.com/genesis-matrix/gema-plr-core
      stack:
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
        - pillarstack.cfg
```
