### ISSUE TITLE
ext_pillar module directory name

### ISSUE THREAD

**Issue by safanaj** [amendlik/gitstack-pillar#2]
according to salt version 2017.7.2 and develop branch:
[here](https://github.com/saltstack/salt/blob/develop/salt/loader.py#L168) and [here](https://github.com/saltstack/salt/blob/develop/salt/loader.py#L349)

the directory _pillars should be renamed to _pillar or fix docs for fileserver_backend to use git section, saying:
```
gitfs_remotes:
  - https://github.com/amendlik/gitstack-pillar.git:
    - root: _pillars
    - mountpoint: _pillar
```
